In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv('dataset.csv')

In [3]:
movies.head()

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811

In [4]:
movies.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='object')

In [5]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10000 non-null  int64
 1   title              10000 non-null  object
 2   genre              9997 non-null   object
 3   original_language  10000 non-null  object
 4   overview           9987 non-null   object
 5   popularity         10000 non-null  float64
 6   release_date       10000 non-null  object
 7   vote_average       10000 non-null  float64
 8   vote_count         10000 non-null  int64
dtypes: float64(2), int64(2), object(5)
memory usage: 703.3+ KB

In [6]:
movies['tags'] = movies['genre'] + movies['overview']

In [7]:
movies.head()

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count,tags
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862,"Drama,CrimeFramed in the 1940s for the double ..."
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731,"Comedy,Drama,RomanceRaj is a rich, carefree, h..."
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280,"Drama,CrimeSpanning the years 1945 to 1955, a ..."
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959,"Drama,History,WarThe true story of how busines..."
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811,"Drama,CrimeIn the continuing saga of the Corle..."

In [8]:
new_df = movies[['id','title','genre','overview','tags']]

In [9]:
new_df.head()

,id,title,genre,overview,tags
0,278,The Shawshank Redemption,"Drama,Crime",Framed in the 1940s for the double murder of h...,"Drama,CrimeFramed in the 1940s for the double ..."
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance","Raj is a rich, carefree, happy-go-lucky second...","Comedy,Drama,RomanceRaj is a rich, carefree, h..."
2,238,The Godfather,"Drama,Crime","Spanning the years 1945 to 1955, a chronicle o...","Drama,CrimeSpanning the years 1945 to 1955, a ..."
3,424,Schindler's List,"Drama,History,War",The true story of how businessman Oskar Schind...,"Drama,History,WarThe true story of how busines..."
4,240,The Godfather: Part II,"Drama,Crime",In the continuing saga of the Corleone crime f...,"Drama,CrimeIn the continuing saga of the Corle..."

In [10]:
new_df = new_df.drop(columns=['genre','overview'])

In [11]:
new_df.head()

,id,title,tags
0,278,The Shawshank Redemption,"Drama,CrimeFramed in the 1940s for the double ..."
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,RomanceRaj is a rich, carefree, h..."
2,238,The Godfather,"Drama,CrimeSpanning the years 1945 to 1955, a ..."
3,424,Schindler's List,"Drama,History,WarThe true story of how busines..."
4,240,The Godfather: Part II,"Drama,CrimeIn the continuing saga of the Corle..."

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
cv = CountVectorizer(max_features=10000,stop_words='english')

In [14]:
cv

CountVectorizer(max_features=10000, stop_words='english')

In [15]:
vec = cv.fit_transform(new_df['tags'].values.astype('U')).toarray()

In [16]:
vec

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [17]:
vec.shape

(10000, 10000)

In [18]:
from sklearn.metrics.pairwise import cosine_similarity

In [19]:
sim = cosine_similarity(vec)

In [20]:
sim

array([[1.        , 0.06253054, 0.05802589, ..., 0.07963978, 0.07597372,
        0.03798686],
       [0.06253054, 1.        , 0.08980265, ..., 0.        , 0.        ,
        0.        ],
       [0.05802589, 0.08980265, 1.        , ..., 0.02541643, 0.03636965,
        0.        ],
       ...,
       [0.07963978, 0.        , 0.02541643, ..., 1.        , 0.03327792,
        0.03327792],
       [0.07597372, 0.        , 0.03636965, ..., 0.03327792, 1.        ,
        0.04761905],
       [0.03798686, 0.        , 0.        , ..., 0.03327792, 0.04761905,
        1.        ]])

In [21]:
new_df[new_df['title']=='The Shawshank Redemption']

,id,title,tags
0,278,The Shawshank Redemption,"Drama,CrimeFramed in the 1940s for the double ..."

In [22]:
dist = sorted(list(enumerate(sim[0])),reverse=True,key=lambda vec:vec[1])

In [23]:
dist

[(0, np.float64(1.0000000000000002)),
 (3709, np.float64(0.23539595453459988)),
 (3649, np.float64(0.22019275302527214)),
 (9006, np.float64(0.20751433915982243)),
 (2605, np.float64(0.20100756305184245)),
 (4068, np.float64(0.20100756305184245)),
 (6156, np.float64(0.20100756305184245)),
 (698, np.float64(0.19894589252079753)),
 (7324, np.float64(0.19767387315371682)),
 (1009, np.float64(0.19069251784911848)),
 (884, np.float64(0.1899342940993966)),
 (2963, np.float64(0.18802535827258876)),
 (7478, np.float64(0.1877810107252081)),
 (2991, np.float64(0.1860968420796942)),
 (715, np.float64(0.18582615562066462)),
 (7271, np.float64(0.18556740475630137)),
 (9520, np.float64(0.18148850216015694)),
 (2120, np.float64(0.17978662999019787)),
 (4201, np.float64(0.17912443020795962)),
 (9718, np.float64(0.17766726362967541)),
 (2796, np.float64(0.17407765595569785)),
 (4063, np.float64(0.17407765595569785)),
 (4295, np.float64(0.17407765595569785)),
 (4491, np.float64(0.17407765595569785)),
 (4490, np.float64(0.17170914210964275)),
 (5428, np.float64(0.17170914210964275)),
 (9139, np.float64(0.17063023229633048)),
 (2081, np.float64(0.16888013236829963)),
 (4222, np.float64(0.16888013236829963)),
 (6758, np.float64(0.16888013236829963)),
 (7418, np.float64(0.16888013236829963)),
 (7471, np.float64(0.16888013236829963)),
 (725, np.float64(0.16514456476895412)),
 (791, np.float64(0.16514456476895412)),
 (2225, np.float64(0.16514456476895412)),
 (3159, np.float64(0.16514456476895412)),
 (393, np.float64(0.1651445647689541)),
 (1068, np.float64(0.16448792373994225)),
 (2925, np.float64(0.16412198797244368)),
 (2927, np.float64(0.16412198797244368)),
 (7558, np.float64(0.16412198797244368)),
 (9756, np.float64(0.16412198797244368)),
 (1038, np.float64(0.15974461276617435)),
 (6402, np.float64(0.15974461276617435)),
 (7884, np.float64(0.15974461276617435)),
 (1175, np.float64(0.1592795619605697)),
 (2583, np.float64(0.15891043154093204)),
 (663, np.float64(0.15745916432444343)),
 (531, np.float64(0.1574591643244434)),
 (2626, np.float64(0.1574591643244434)),
 (5027, np.float64(0.1574591643244434)),
 (1507, np.float64(0.15632634987018063)),
 (4942, np.float64(0.15632634987018063)),
 (1264, np.float64(0.15569978883230462)),
 (5587, np.float64(0.15569978883230462)),
 (1619, np.float64(0.1556997888323046)),
 (3833, np.float64(0.1556997888323046)),
 (9475, np.float64(0.1556997888323046)),
 (645, np.float64(0.15386436372416593)),
 (2009, np.float64(0.15386436372416593)),
 (4234, np.float64(0.15386436372416593)),
 (5776, np.float64(0.15386436372416593)),
 (1646, np.float64(0.1523510148357077)),
 (1480, np.float64(0.1519474352795173)),
 (2084, np.float64(0.1519474352795173)),
 (3250, np.float64(0.1519474352795173)),
 (6297, np.float64(0.1519474352795173)),
 (4155, np.float64(0.15151515151515155)),
 (7878, np.float64(0.15151515151515155)),
 (3848, np.float64(0.15075567228888184)),
 (4811, np.float64(0.15075567228888184)),
 (4988, np.float64(0.15075567228888184)),
 (5557, np.float64(0.15075567228888184)),
 (8410, np.float64(0.15075567228888184)),
 (8832, np.float64(0.15075567228888184)),
 (87, np.float64(0.149270358506633)),
 (196, np.float64(0.149270358506633)),
 (279, np.float64(0.149270358506633)),
 (8263, np.float64(0.149270358506633)),
 (3182, np.float64(0.1484539238050411)),
 (4086, np.float64(0.1484539238050411)),
 (6294, np.float64(0.1484539238050411)),
 (8671, np.float64(0.1477097891751993)),
 (6162, np.float64(0.14712247158412495)),
 (7771, np.float64(0.14712247158412495)),
 (441, np.float64(0.14712247158412492)),
 (7921, np.float64(0.14712247158412492)),
 (933, np.float64(0.14519080172812557)),
 (2112, np.float64(0.14519080172812557)),
 (6093, np.float64(0.14519080172812557)),
 (9980, np.float64(0.14506471329641488)),
 (1223, np.float64(0.1448413648755803)),
 (4987, np.float64(0.1448413648755803)),
 (5262, np.float64(0.1448413648755803)),
 (5512, np.float64(0.1448413648755803)),
 (7049, np.float64(0.1448413648755803)),
 (1544, np.float64(0.14309095175803563)),
 (4273, np.float64(0.14309095175803563)),
 (6538, np.float64(0.14309095175803563)),
 (4064, np.float64(0.14261973987987747)),
 (5882, np.float64(0.14213381090374033)),
 (7828, np.float64(0.14213381090374033)),
 (4406, np.float64(0.1411956236812263)),
 (5508, np.float64(0.1411956236812263)),
 (9126, np.float64(0.1411956236812263)),
 (331, np.float64(0.13957263155977065)),
 (989, np.float64(0.13957263155977065)),
 (1516, np.float64(0.13957263155977065)),
 (4296, np.float64(0.13957263155977065)),
 (8086, np.float64(0.13957263155977065)),
 (6418, np.float64(0.13937366833451514)),
 (6561, np.float64(0.13937366833451514)),
 (6862, np.float64(0.13937366833451514)),
 (1191, np.float64(0.1392621247645583)),
 (8030, np.float64(0.1392621247645583)),
 (5182, np.float64(0.1365577483997838)),
 (7599, np.float64(0.1365577483997838)),
 (3762, np.float64(0.13597788272980102)),
 (7871, np.float64(0.13593181195675924)),
 (52, np.float64(0.13483997249264842)),
 (71, np.float64(0.1348399724926484)),
 (143, np.float64(0.1348399724926484)),
 (170, np.float64(0.1348399724926484)),
 (1407, np.float64(0.1348399724926484)),
 (2862, np.float64(0.1348399724926484)),
 (2932, np.float64(0.1348399724926484)),
 (3349, np.float64(0.1348399724926484)),
 (6563, np.float64(0.1348399724926484)),
 (6756, np.float64(0.1348399724926484)),
 (7135, np.float64(0.1348399724926484)),
 (9275, np.float64(0.1348399724926484)),
 (8760, np.float64(0.1343038273375634)),
 (3881, np.float64(0.13400504203456162)),
 (4632, np.float64(0.13400504203456162)),
 (5551, np.float64(0.13400504203456162)),
 (6074, np.float64(0.13400504203456162)),
 (8071, np.float64(0.13400504203456162)),
 (2529, np.float64(0.1315903389919538)),
 (3233, np.float64(0.1315903389919538)),
 (4953, np.float64(0.1315903389919538)),
 (5860, np.float64(0.1315903389919538)),
 (9579, np.float64(0.1315903389919538)),
 (729, np.float64(0.1305582419667734)),
 (1573, np.float64(0.1305582419667734)),
 (2335, np.float64(0.1305582419667734)),
 (2813, np.float64(0.1305582419667734)),
 (4347, np.float64(0.1305582419667734)),
 (4485, np.float64(0.1305582419667734)),
 (4652, np.float64(0.1305582419667734)),
 (6539, np.float64(0.1305582419667734)),
 (6683, np.float64(0.1305582419667734)),
 (6746, np.float64(0.1305582419667734)),
 (7392, np.float64(0.1305582419667734)),
 (9516, np.float64(0.1305582419667734)),
 (834, np.float64(0.1297498240269205)),
 (6284, np.float64(0.1297498240269205)),
 (6850, np.float64(0.1297498240269205)),
 (1599, np.float64(0.1293016367670472)),
 (7395, np.float64(0.1293016367670472)),
 (2011, np.float64(0.12712834523274563)),
 (2936, np.float64(0.12712834523274563)),
 (3042, np.float64(0.12712834523274563)),
 (7544, np.float64(0.12712834523274563)),
 (7756, np.float64(0.12712834523274563)),
 (8540, np.float64(0.12712834523274563)),
 (4905, np.float64(0.12695917902975642)),
 (7677, np.float64(0.12695917902975642)),
 (295, np.float64(0.12666009927622474)),
 (2209, np.float64(0.12666009927622474)),
 (2500, np.float64(0.12666009927622474)),
 (3164, np.float64(0.12666009927622474)),
 (3242, np.float64(0.12666009927622474)),
 (3359, np.float64(0.12666009927622474)),
 (3893, np.float64(0.12666009927622474)),
 (4052, np.float64(0.12666009927622474)),
 (4403, np.float64(0.12666009927622474)),
 (5394, np.float64(0.12666009927622474)),
 (5843, np.float64(0.12666009927622474)),
 (6327, np.float64(0.12666009927622474)),
 (6458, np.float64(0.12666009927622474)),
 (7993, np.float64(0.12666009927622474)),
 (8115, np.float64(0.12666009927622474)),
 (8206, np.float64(0.12666009927622474)),
 (8274, np.float64(0.12666009927622474)),
 (8800, np.float64(0.12666009927622474)),
 (8917, np.float64(0.12666009927622474)),
 (9818, np.float64(0.12666009927622474)),
 (6277, np.float64(0.12562972690740154)),
 (9766, np.float64(0.12562972690740154)),
 (1193, np.float64(0.1250610798961445)),
 (2712, np.float64(0.1250610798961445)),
 (7533, np.float64(0.1250610798961445)),
 (4071, np.float64(0.12434118282549846)),
 (159, np.float64(0.12309149097933275)),
 (501, np.float64(0.12309149097933275)),
 (552, np.float64(0.12309149097933275)),
 (919, np.float64(0.12309149097933275)),
 (1105, np.float64(0.12309149097933275)),
 (1120, np.float64(0.12309149097933275)),
 (1145, np.float64(0.12309149097933275)),
 (2028, np.float64(0.12309149097933275)),
 (2219, np.float64(0.12309149097933275)),
 (2330, np.float64(0.12309149097933275)),
 (3187, np.float64(0.12309149097933275)),
 (4378, np.float64(0.12309149097933275)),
 (5290, np.float64(0.12309149097933275)),
 (6459, np.float64(0.12309149097933275)),
 (7255, np.float64(0.12309149097933275)),
 (7440, np.float64(0.12309149097933275)),
 (8266, np.float64(0.12309149097933275)),
 (1447, np.float64(0.12309149097933274)),
 (3508, np.float64(0.12309149097933274)),
 (3617, np.float64(0.12309149097933274)),
 (6892, np.float64(0.12309149097933274)),
 (7166, np.float64(0.12309149097933274)),
 (6254, np.float64(0.12187873735452176)),
 (313, np.float64(0.12121212121212123)),
 (3789, np.float64(0.12121212121212123)),
 (5119, np.float64(0.12121212121212123)),
 (7153, np.float64(0.12121212121212123)),
 (138, np.float64(0.11980845957463077)),
 (955, np.float64(0.11980845957463077)),
 (1976, np.float64(0.11980845957463077)),
 (2136, np.float64(0.11980845957463077)),
 (2392, np.float64(0.11980845957463077)),
 (3026, np.float64(0.11980845957463077)),
 (3296, np.float64(0.11980845957463077)),
 (3507, np.float64(0.11980845957463077)),
 (3884, np.float64(0.11980845957463077)),
 (5257, np.float64(0.11980845957463077)),
 (5434, np.float64(0.11980845957463077)),
 (5525, np.float64(0.11980845957463077)),
 (5700, np.float64(0.11980845957463077)),
 (7809, np.float64(0.11980845957463077)),
 (8085, np.float64(0.11980845957463077)),
 (8503, np.float64(0.11980845957463077)),
 (9587, np.float64(0.11980845957463077)),
 (3906, np.float64(0.11955702496470261)),
 (6799, np.float64(0.11955702496470261)),
 (747, np.float64(0.11941628680530642)),
 (2695, np.float64(0.11941628680530642)),
 (2945, np.float64(0.11897966272250736)),
 (168, np.float64(0.11769797726729994)),
 (1287, np.float64(0.11769797726729994)),
 (1537, np.float64(0.11769797726729994)),
 (4377, np.float64(0.11769797726729994)),
 (8351, np.float64(0.11769797726729994)),
 (408, np.float64(0.11736313170325507)),
 (3292, np.float64(0.11736313170325507)),
 (4077, np.float64(0.11736313170325507)),
 (1542, np.float64(0.11677484162422844)),
 (2106, np.float64(0.11677484162422844)),
 (2230, np.float64(0.11677484162422844)),
 (2522, np.float64(0.11677484162422844)),
 (2659, np.float64(0.11677484162422844)),
 (2726, np.float64(0.11677484162422844)),
 (3413, np.float64(0.11677484162422844)),
 (3453, np.float64(0.11677484162422844)),
 (3621, np.float64(0.11677484162422844)),
 (4023, np.float64(0.11677484162422844)),
 (4141, np.float64(0.11677484162422844)),
 (4300, np.float64(0.11677484162422844)),
 (4302, np.float64(0.11677484162422844)),
 (4767, np.float64(0.11677484162422844)),
 (5728, np.float64(0.11677484162422844)),
 (7411, np.float64(0.11677484162422844)),
 (7851, np.float64(0.11677484162422844)),
 (841, np.float64(0.1160517706371319)),
 (865, np.float64(0.1160517706371319)),
 (1477, np.float64(0.1160517706371319)),
 (1754, np.float64(0.1160517706371319)),
 (2786, np.float64(0.1160517706371319)),
 (3456, np.float64(0.1160517706371319)),
 (3670, np.float64(0.1160517706371319)),
 (4271, np.float64(0.1160517706371319)),
 (4850, np.float64(0.1160517706371319)),
 (6243, np.float64(0.1160517706371319)),
 (6970, np.float64(0.1160517706371319)),
 (7325, np.float64(0.1160517706371319)),
 (8638, np.float64(0.1160517706371319)),
 (9363, np.float64(0.11528574397767913)),
 (7505, np.float64(0.1144727614064285)),
 (8538, np.float64(0.1144727614064285)),
 (8640, np.float64(0.1142875802206236)),
 (819, np.float64(0.11396057645963797)),
 (1034, np.float64(0.11396057645963797)),
 (1489, np.float64(0.11396057645963797)),
 (1657, np.float64(0.11396057645963797)),
 (2160, np.float64(0.11396057645963797)),
 (2453, np.float64(0.11396057645963797)),
 (3234, np.float64(0.11396057645963797)),
 (3937, np.float64(0.11396057645963797)),
 (5684, np.float64(0.11396057645963797)),
 (6753, np.float64(0.11396057645963797)),
 (7323, np.float64(0.11396057645963797)),
 (7766, np.float64(0.11396057645963797)),
 (8242, np.float64(0.11396057645963797)),
 (8313, np.float64(0.11396057645963797)),
 (8935, np.float64(0.11396057645963797)),
 (9138, np.float64(0.11396057645963797)),
 (6232, np.float64(0.11331490227483418)),
 (6308, np.float64(0.11295649894498103)),
 (7076, np.float64(0.11295649894498103)),
 (2352, np.float64(0.11236664374387367)),
 (1918, np.float64(0.11149893466761211)),
 (2966, np.float64(0.11149893466761211)),
 (4462, np.float64(0.11149893466761211)),
 (252, np.float64(0.11134044285378084)),
 (608, np.float64(0.11134044285378084)),
 (1625, np.float64(0.11134044285378084)),
 (1775, np.float64(0.11134044285378084)),
 (1958, np.float64(0.11134044285378084)),
 (1970, np.float64(0.11134044285378084)),
 (2148, np.float64(0.11134044285378084)),
 (3514, np.float64(0.11134044285378084)),
 (3611, np.float64(0.11134044285378084)),
 (3983, np.float64(0.11134044285378084)),
 (4569, np.float64(0.11134044285378084)),
 (4620, np.float64(0.11134044285378084)),
 (4885, np.float64(0.11134044285378084)),
 (7081, np.float64(0.11134044285378084)),
 (9669, np.float64(0.11134044285378084)),
 (1449, np.float64(0.11134044285378082)),
 (456, np.float64(0.11009637651263607)),
 (1822, np.float64(0.11009637651263607)),
 (2238, np.float64(0.11009637651263607)),
 (4330, np.float64(0.11009637651263607)),
 (4590, np.float64(0.11009637651263607)),
 (4895, np.float64(0.11009637651263607)),
 (5089, np.float64(0.11009637651263607)),
 (5224, np.float64(0.11009637651263607)),
 (6696, np.float64(0.11009637651263607)),
 (6822, np.float64(0.11009637651263607)),
 (7245, np.float64(0.11009637651263607)),
 (278, np.float64(0.10889310129609417)),
 (547, np.float64(0.10889310129609417)),
 (869, np.float64(0.10889310129609417)),
 (960, np.float64(0.10889310129609417)),
 (976, np.float64(0.10889310129609417)),
 (1993, np.float64(0.10889310129609417)),
 (2426, np.float64(0.10889310129609417)),
 (3600, np.float64(0.10889310129609417)),
 (5456, np.float64(0.10889310129609417)),
 (5947, np.float64(0.10889310129609417)),
 (6974, np.float64(0.10889310129609417)),
 (8128, np.float64(0.10889310129609417)),
 (8555, np.float64(0.10889310129609417)),
 (336, np.float64(0.10874544956540738)),
 (2654, np.float64(0.10874544956540738)),
 (3277, np.float64(0.10874544956540738)),
 (7407, np.float64(0.10874544956540738)),
 (7792, np.float64(0.10874544956540738)),
 (1430, np.float64(0.10744306187005072)),
 (3269, np.float64(0.10744306187005072)),
 (3537, np.float64(0.10744306187005072)),
 (8249, np.float64(0.10744306187005072)),
 (8755, np.float64(0.10744306187005072)),
 (511, np.float64(0.10660035817780525)),
 (1298, np.float64(0.10660035817780525)),
 (2164, np.float64(0.10660035817780525)),
 (2472, np.float64(0.10660035817780525)),
 (3458, np.float64(0.10660035817780525)),
 (4078, np.float64(0.10660035817780525)),
 (4223, np.float64(0.10660035817780525)),
 (4608, np.float64(0.10660035817780525)),
 (4689, np.float64(0.10660035817780525)),
 (4894, np.float64(0.10660035817780525)),
 (5675, np.float64(0.10660035817780525)),
 (5908, np.float64(0.10660035817780525)),
 (6175, np.float64(0.10660035817780525)),
 (6716, np.float64(0.10660035817780525)),
 (9173, np.float64(0.10660035817780525)),
 (9397, np.float64(0.10660035817780525)),
 (541, np.float64(0.10618637464037979)),
 (9745, np.float64(0.10618637464037979)),
 (36, np.float64(0.10497277621629561)),
 (190, np.float64(0.10497277621629561)),
 (322, np.float64(0.10497277621629561)),
 (470, np.float64(0.10497277621629561)),
 (671, np.float64(0.10497277621629561)),
 (903, np.float64(0.10497277621629561)),
 (991, np.float64(0.10497277621629561)),
 (1349, np.float64(0.10497277621629561)),
 (1533, np.float64(0.10497277621629561)),
 (1636, np.float64(0.10497277621629561)),
 (1988, np.float64(0.10497277621629561)),
 (2856, np.float64(0.10497277621629561)),
 (3013, np.float64(0.10497277621629561)),
 (3365, np.float64(0.10497277621629561)),
 (3474, np.float64(0.10497277621629561)),
 (4395, np.float64(0.10497277621629561)),
 (5176, np.float64(0.10497277621629561)),
 (5410, np.float64(0.10497277621629561)),
 (5985, np.float64(0.10497277621629561)),
 (6337, np.float64(0.10497277621629561)),
 (7853, np.float64(0.10497277621629561)),
 (9113, np.float64(0.10497277621629561)),
 (825, np.float64(0.10444659357341872)),
 (1039, np.float64(0.10444659357341872)),
 (1881, np.float64(0.10444659357341872)),
 (3263, np.float64(0.10444659357341872)),
 (5297, np.float64(0.10444659357341872)),
 (5965, np.float64(0.10444659357341872)),
 (6262, np.float64(0.10444659357341872)),
 (8747, np.float64(0.10444659357341872)),
 (8841, np.float64(0.10379985922153641)),
 (2353, np.float64(0.10266540046786908)),
 (2568, np.float64(0.10266540046786908)),
 (3033, np.float64(0.10266540046786908)),
 (5876, np.float64(0.10266540046786908)),
 (8168, np.float64(0.10266540046786908)),
 (6762, np.float64(0.1025762424827773)),
 (6963, np.float64(0.1025762424827773)),
 (28, np.float64(0.10241831129983785)),
 (70, np.float64(0.10241831129983785)),
 (731, np.float64(0.10241831129983785)),
 (1133, np.float64(0.10241831129983785)),
 (1834, np.float64(0.10241831129983785)),
 (1853, np.float64(0.10241831129983785)),
 (2673, np.float64(0.10241831129983785)),
 (4534, np.float64(0.10241831129983785)),
 (4562, np.float64(0.10241831129983785)),
 (6527, np.float64(0.10241831129983785)),
 (6531, np.float64(0.10241831129983785)),
 (6607, np.float64(0.10241831129983785)),
 (7003, np.float64(0.10241831129983785)),
 (7196, np.float64(0.10241831129983785)),
 (8646, np.float64(0.10241831129983785)),
 (9077, np.float64(0.10241831129983785)),
 (4512, np.float64(0.10156734322380512)),
 (50, np.float64(0.10050378152592122)),
 (437, np.float64(0.10050378152592122)),
 (1016, np.float64(0.10050378152592122)),
 (1201, np.float64(0.10050378152592122)),
 (1216, np.float64(0.10050378152592122)),
 (1258, np.float64(0.10050378152592122)),
 (1773, np.float64(0.10050378152592122)),
 (1954, np.float64(0.10050378152592122)),
 (1956, np.float64(0.10050378152592122)),
 (2049, np.float64(0.10050378152592122)),
 (2050, np.float64(0.10050378152592122)),
 (2169, np.float64(0.10050378152592122)),
 (2228, np.float64(0.10050378152592122)),
 (2306, np.float64(0.10050378152592122)),
 (2362, np.float64(0.10050378152592122)),
 (2412, np.float64(0.10050378152592122)),
 (2462, np.float64(0.10050378152592122)),
 (2616, np.float64(0.10050378152592122)),
 (2758, np.float64(0.10050378152592122)),
 (2766, np.float64(0.10050378152592122)),
 (2853, np.float64(0.10050378152592122)),
 (2907, np.float64(0.10050378152592122)),
 (3108, np.float64(0.10050378152592122)),
 (3493, np.float64(0.10050378152592122)),
 (3645, np.float64(0.10050378152592122)),
 (3690, np.float64(0.10050378152592122)),
 (5193, np.float64(0.10050378152592122)),
 (5676, np.float64(0.10050378152592122)),
 (5973, np.float64(0.10050378152592122)),
 (6279, np.float64(0.10050378152592122)),
 (6432, np.float64(0.10050378152592122)),
 (6965, np.float64(0.10050378152592122)),
 (6990, np.float64(0.10050378152592122)),
 (7543, np.float64(0.10050378152592122)),
 (8297, np.float64(0.10050378152592122)),
 (8399, np.float64(0.10050378152592122)),
 (8637, np.float64(0.10050378152592122)),
 (8687, np.float64(0.10050378152592122)),
 (9493, np.float64(0.10050378152592122)),
 (839, np.float64(0.10050378152592121)),
 (3756, np.float64(0.10050378152592121)),
 (3883, np.float64(0.10050378152592121)),
 (4848, np.float64(0.10050378152592121)),
 (5175, np.float64(0.10050378152592121)),
 (7071, np.float64(0.10050378152592121)),
 (9124, np.float64(0.10050378152592121)),
 (9804, np.float64(0.10050378152592121)),
 (1659, np.float64(0.09947294626039876)),
 (7350, np.float64(0.09947294626039876)),
 (7390, np.float64(0.09947294626039876)),

In [24]:
for i in dist [0:5]:
  print(new_df.iloc[i[0]].title)

The Shawshank Redemption
Anything for Her
The Woodsman
The Getaway
Pusher II

In [25]:
def recommend(movies):
  index = new_df[new_df['title']==movies].index[0]
  distance = sorted(list(enumerate(sim[index])),reverse=True,key=lambda vec:vec[1])
  for i in distance [0:5]:
    print(new_df.iloc[i[0]].title)

In [26]:
recommend ("Iron Man")

Iron Man
Mazinger Z: Infinity
Justice League Dark
Iron Man 3
The Colony

In [27]:
recommend('Justice League Dark')

Justice League Dark
Spectral
Race to Witch Mountain
Atlantis: Milo's Return
Abraham Lincoln: Vampire Hunter

In [28]:
recommend('Pusher II')

Pusher II
The Unforgivable
Shot Caller
Gotti
Angst

In [29]:
recommend('Angst')

Angst
The Pledge
Hush
The Bad Seed
The Orphanage

In [30]:
recommend("The Bad Seed")

The Bad Seed
Within
Angst
The Pledge
Hush

In [31]:
recommend("Gladiator")

Gladiator
In Hell
Ben-Hur
The Fugitive
Agora

In [32]:
recommend('Troy')

Troy
Tae Guk Gi: The Brotherhood of War
The Mummy: Tomb of the Dragon Emperor
Mirai
Horton Hears a Who!